name: chat_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6
#  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  shelf: ^1.4.0
  shelf_web_socket: ^1.0.0
  web_socket_channel: ^2.2.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
